/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-10-23 09:41:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(session.getAttribute("name")==null){
		response.sendRedirect("login.jsp");
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"author\" content=\"\" />\n");
      out.write("<title>My Login & Sign up page</title>\n");
      out.write("<!-- Favicon-->\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\n");
      out.write("<!-- Font Awesome icons (free version)-->\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.15.4/js/all.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- Google fonts-->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("<link href=\"css/index-styles.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("<body id=\"page-top\">\n");
      out.write("	<!-- Navigation-->\n");
      out.write("	<nav\n");
      out.write("		class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\"\n");
      out.write("		id=\"mainNav\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<a class=\"navbar-brand\" href=\"#page-top\">Java Developer</a>\n");
      out.write("			<button\n");
      out.write("				class=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\"\n");
      out.write("				type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("				data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("				Menu <i class=\"fas fa-bars\"></i>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#portfolio\">Portfolio</a></li>\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#about\">About</a></li>\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#contact\">Contact</a></li>\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"logout\">Logout</a></li>\n");
      out.write("					<li class=\"nav-item mx-0 mx-lg-1 bg-danger\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"logout\">");
      out.print(session.getAttribute("name") );
      out.write("</a></li>\n");
      out.write("					\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<!-- Masthead-->\n");
      out.write("	<header class=\"masthead bg-primary text-white text-center\">\n");
      out.write("		<div class=\"container d-flex align-items-center flex-column\">\n");
      out.write("			<!-- Masthead Avatar Image-->\n");
      out.write("			<img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\"\n");
      out.write("				alt=\"...\" />\n");
      out.write("			<!-- Masthead Heading-->\n");
      out.write("			<h1 class=\"masthead-heading text-uppercase mb-0\">Welcome Java Developers</h1>\n");
      out.write("			<!-- Icon Divider-->\n");
      out.write("			<div class=\"divider-custom divider-light\">\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("				<div class=\"divider-custom-icon\">\n");
      out.write("					<i class=\"fas fa-star\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("			</div>\n");
      out.write("			<!-- Masthead Subheading-->\n");
      out.write("			<p class=\"masthead-subheading font-weight-light mb-0\">Java Development - Web Development</p>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("	<!-- Portfolio Section-->\n");
      out.write("	<section class=\"page-section portfolio\" id=\"portfolio\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<!-- Portfolio Section Heading-->\n");
      out.write("			<h2\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\n");
      out.write("			<!-- Icon Divider-->\n");
      out.write("			<div class=\"divider-custom\">\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("				<div class=\"divider-custom-icon\">\n");
      out.write("					<i class=\"fas fa-star\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("			</div>\n");
      out.write("			<!-- Portfolio Grid Items-->\n");
      out.write("			<div class=\"row justify-content-center\">\n");
      out.write("				<!-- Portfolio Item 1-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal1\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/cabin.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- Portfolio Item 2-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal2\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/cake.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- Portfolio Item 3-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal3\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/circus.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- Portfolio Item 4-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal4\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/game.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- Portfolio Item 5-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal5\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/safe.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- Portfolio Item 6-->\n");
      out.write("				<div class=\"col-md-6 col-lg-4\">\n");
      out.write("					<div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\"\n");
      out.write("						data-bs-target=\"#portfolioModal6\">\n");
      out.write("						<div\n");
      out.write("							class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\n");
      out.write("							<div\n");
      out.write("								class=\"portfolio-item-caption-content text-center text-white\">\n");
      out.write("								<i class=\"fas fa-plus fa-3x\"></i>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<img class=\"img-fluid\" src=\"assets/img/portfolio/submarine.png\"\n");
      out.write("							alt=\"...\" />\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!-- About Section-->\n");
      out.write("	<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<!-- About Section Heading-->\n");
      out.write("			<h2\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\n");
      out.write("			<!-- Icon Divider-->\n");
      out.write("			<div class=\"divider-custom divider-light\">\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("				<div class=\"divider-custom-icon\">\n");
      out.write("					<i class=\"fas fa-star\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("			</div>\n");
      out.write("			<!-- About Section Content-->\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-4 ms-auto\">\n");
      out.write("					<p class=\"lead\">Software Developer with a passion for developing scalable web applications \n");
      out.write("					and working across the full stack. I am looking for an opportunity to work for an organization \n");
      out.write("					and utilize my skills acquired for self-development and the growth of the organization.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-lg-4 me-auto\">\n");
      out.write("					<p class=\"lead\">You can create your own custom avatar for the\n");
      out.write("						masthead, change the icon in the dividers, and add your email\n");
      out.write("						address to the contact form to make it fully functional!</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- About Section Button-->\n");
      out.write("			<div class=\"text-center mt-4\">\n");
      out.write("				<a class=\"btn btn-xl btn-outline-light\"\n");
      out.write("					href=\"/signupProject/Resume/HarishDubey_Resume02.pdf\"> \n");
      out.write("					<i class=\"fas fa-download me-2\"></i> Free Download!\n");
      out.write("				</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!-- Contact Section-->\n");
      out.write("	<section class=\"page-section\" id=\"contact\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<!-- Contact Section Heading-->\n");
      out.write("			<h2\n");
      out.write("				class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Contact\n");
      out.write("				Me</h2>\n");
      out.write("			<!-- Icon Divider-->\n");
      out.write("			<div class=\"divider-custom\">\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("				<div class=\"divider-custom-icon\">\n");
      out.write("					<i class=\"fas fa-star\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"divider-custom-line\"></div>\n");
      out.write("			</div>\n");
      out.write("			<!-- Contact Section Form-->\n");
      out.write("<div class=\"row justify-content-center\">\n");
      out.write("    <div class=\"col-lg-8 col-xl-7\">\n");
      out.write("        <form id=\"contactForm\">\n");
      out.write("            <!-- Name input-->\n");
      out.write("            <div class=\"form-floating mb-3\">\n");
      out.write("                <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Enter your name...\" required />\n");
      out.write("                <label for=\"name\">Full name</label>\n");
      out.write("                <div class=\"invalid-feedback\">A name is required.</div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Email address input-->\n");
      out.write("            <div class=\"form-floating mb-3\">\n");
      out.write("                <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"name@example.com\" required />\n");
      out.write("                <label for=\"email\">Email address</label>\n");
      out.write("                <div class=\"invalid-feedback\">An email is required.</div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Phone number input-->\n");
      out.write("            <div class=\"form-floating mb-3\">\n");
      out.write("                <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"(123) 456-7890\" required />\n");
      out.write("                <label for=\"phone\">Phone number</label>\n");
      out.write("                <div class=\"invalid-feedback\">A phone number is required.</div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Message input-->\n");
      out.write("            <div class=\"form-floating mb-3\">\n");
      out.write("                <textarea class=\"form-control\" id=\"message\" type=\"text\" placeholder=\"Enter your message here...\" style=\"height: 10rem\" required></textarea>\n");
      out.write("                <label for=\"message\">Message</label>\n");
      out.write("                <div class=\"invalid-feedback\">A message is required.</div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Submit Button-->\n");
      out.write("            <button class=\"btn btn-primary btn-xl\" id=\"submitButton\" type=\"submit\">Send</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <!-- Thank you message -->\n");
      out.write("        <div id=\"thankYouMessage\" style=\"display:none; margin-top: 20px;\">\n");
      out.write("            <h3>Thank you for your message!</h3>\n");
      out.write("            <p>We will get back to you shortly.</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- JavaScript to handle form submission and display Thank You message -->\n");
      out.write("<script>\n");
      out.write("    document.getElementById('contactForm').addEventListener('submit', function(event) {\n");
      out.write("        event.preventDefault(); // Prevent form from submitting\n");
      out.write("        // Hide the form and display the thank you message\n");
      out.write("        document.getElementById('contactForm').style.display = 'none';\n");
      out.write("        document.getElementById('thankYouMessage').style.display = 'block';\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("	<!-- Footer-->\n");
      out.write("<footer class=\"footer text-center\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <!-- Footer Location-->\n");
      out.write("            <div class=\"col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("                <h4 class=\"text-uppercase mb-4\">Location</h4>\n");
      out.write("                <p class=\"lead mb-0\">\n");
      out.write("                    Btm 2nd Stage <br /> Bengaluru, India.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <!-- Footer Social Icons-->\n");
      out.write("            <div class=\"col-lg-4 mb-5 mb-lg-0\">\n");
      out.write("                <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\n");
      out.write("                <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\n");
      out.write("                <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-twitter\"></i></a>\n");
      out.write("                <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a>\n");
      out.write("                <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-dribbble\"></i></a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Footer About Text-->\n");
      out.write("            <div class=\"col-lg-4\">\n");
      out.write("                <h4 class=\"text-uppercase mb-4\">About</h4>\n");
      out.write("                <p class=\"lead mb-0\">\n");
      out.write("                    Feel free to connect with me \n");
      out.write("                <a href=\"https://mail.google.com/mail/?view=cm&fs=1&to=harishdubey98r@gmail.com\" target=\"_blank\">Harish Dubey</a>.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("	<!-- Copyright Section-->\n");
      out.write("	<div class=\"copyright py-4 text-center text-white\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<small>Copyright &copy; Your Website 2024</small>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modals-->\n");
      out.write("	<!-- Portfolio Modal 1-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal1\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Log\n");
      out.write("									Cabin</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/cabin.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Log Cabin - A log cabin is a small, rustic house made from logs, \n");
      out.write("								often associated with early American frontier life. It typically features a simple, \n");
      out.write("								sturdy design and evokes a sense of nostalgia and connection to nature.</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modal 2-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal2\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Tasty Cake</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/cake.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Tasty Cake - Tasty Cake is a brand known for its baked goods, \n");
      out.write("								especially snack cakes, pies, and cupcakes. Originating in the early 20th century, \n");
      out.write("								itâs famous for its sweet, indulgent treats enjoyed by many.</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modal 3-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal3\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Circus Tent</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/circus.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Circus Tent - A circus tent is a large, colorful fabric structure that serves as the venue for \n");
      out.write("								circus performances. Typically featuring a peaked roof and vibrant patterns, it creates a festive atmosphere for \n");
      out.write("								acrobats, clowns, and animal acts.</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modal 4-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal4\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Game Controller</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/game.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Game Controller - A game controller is a handheld device used to interact with video games. \n");
      out.write("								It typically features buttons, joysticks, and triggers, allowing players to control characters and navigate \n");
      out.write("								game environments. Controllers come in various designs for consoles, PCs, and mobile devices..</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modal 5-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal5\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Locked Safe</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/safe.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Locked Safe - A locked safe is a secure storage container designed to protect valuable items, \n");
      out.write("								documents, or money. It features a locking mechanism, often with a combination or key, ensuring that only \n");
      out.write("								authorized users can access its contents. Safes are commonly used for home security and in businesses.</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Portfolio Modal 6-->\n");
      out.write("	<div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\"\n");
      out.write("		tabindex=\"-1\" aria-labelledby=\"portfolioModal6\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-xl\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header border-0\">\n");
      out.write("					<button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body text-center pb-5\">\n");
      out.write("					<div class=\"container\">\n");
      out.write("						<div class=\"row justify-content-center\">\n");
      out.write("							<div class=\"col-lg-8\">\n");
      out.write("								<!-- Portfolio Modal - Title-->\n");
      out.write("								<h2\n");
      out.write("									class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Submarine</h2>\n");
      out.write("								<!-- Icon Divider-->\n");
      out.write("								<div class=\"divider-custom\">\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("									<div class=\"divider-custom-icon\">\n");
      out.write("										<i class=\"fas fa-star\"></i>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"divider-custom-line\"></div>\n");
      out.write("								</div>\n");
      out.write("								<!-- Portfolio Modal - Image-->\n");
      out.write("								<img class=\"img-fluid rounded mb-5\"\n");
      out.write("									src=\"assets/img/portfolio/submarine.png\" alt=\"...\" />\n");
      out.write("								<!-- Portfolio Modal - Text-->\n");
      out.write("								<p class=\"mb-4\">Submarine - A submarine is a watercraft capable of underwater operation. It can dive below the surface \n");
      out.write("								for military, research, or exploration purposes. Submarines are equipped with advanced technology for navigation, \n");
      out.write("								communication, and weaponry, and they can stay submerged for extended periods..</p>\n");
      out.write("								<button class=\"btn btn-primary\" href=\"#!\"\n");
      out.write("									data-bs-dismiss=\"modal\">\n");
      out.write("									<i class=\"fas fa-times fa-fw\"></i> Close Window\n");
      out.write("								</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Bootstrap core JS-->\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<!-- Core theme JS-->\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
